tailwind.config = {
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        "on-secondary": "#520072",
        "surface-container-low": "#191c22",
        outline: "#849495",
        "surface-bright": "#363940",
        "surface-container-high": "#272a31",
        "on-secondary-fixed-variant": "#74009f",
        "tertiary-fixed": "#ffdadb",
        "on-tertiary-fixed-variant": "#91002d",
        "on-surface-variant": "#b9cacb",
        "on-tertiary-container": "#be003d",
        "on-primary-container": "#006970",
        error: "#ffb4ab",
        "inverse-on-surface": "#2e3037",
        "primary-container": "#00f0ff",
        background: "#10131a",
        "on-surface": "#e1e2eb",
        "inverse-primary": "#006970",
        "on-primary-fixed": "#002022",
        tertiary: "#fff3f3",
        "secondary-fixed": "#f8d8ff",
        "secondary-fixed-dim": "#ebb2ff",
        "primary-fixed-dim": "#00dbe9",
        "on-error-container": "#ffdad6",
        "surface-container": "#1d2026",
        "on-secondary-fixed": "#320047",
        "primary-fixed": "#7df4ff",
        "on-background": "#e1e2eb",
        "outline-variant": "#3b494b",
        "tertiary-fixed-dim": "#ffb2b8",
        "tertiary-container": "#ffcdd0",
        "error-container": "#93000a",
        "secondary-container": "#b600f8",
        surface: "#10131a",
        "on-error": "#690005",
        "on-primary-fixed-variant": "#004f54",
        "surface-variant": "#32353c",
        secondary: "#ebb2ff",
        "on-tertiary-fixed": "#40000f",
        "surface-tint": "#00dbe9",
        "surface-container-highest": "#32353c",
        "on-primary": "#00363a",
        primary: "#dbfcff",
        "surface-dim": "#10131a",
        "on-secondary-container": "#fff6fc",
        "inverse-surface": "#e1e2eb",
        "surface-container-lowest": "#0b0e14",
        "on-tertiary": "#67001d",
      },
      borderRadius: {
        DEFAULT: "0.25rem",
        lg: "0.5rem",
        xl: "0.75rem",
        full: "9999px",
      },
      spacing: {
        "margin-desktop": "64px",
        unit: "4px",
        "container-max": "1440px",
        gutter: "24px",
        "margin-mobile": "20px",
      },
      fontFamily: {
        "headline-lg": ["anybody"],
        "label-mono": ["Space Mono"],
        "display-xl-mobile": ["anybody"],
        "body-md": ["geist"],
        "headline-lg-mobile": ["anybody"],
        "display-xl": ["anybody"],
      },
      fontSize: {
        "headline-lg": ["40px", { lineHeight: "48px", letterSpacing: "0.02em", fontWeight: "700" }],
        "label-mono": ["12px", { lineHeight: "16px", letterSpacing: "0.1em", fontWeight: "700" }],
        "display-xl-mobile": ["48px", { lineHeight: "48px", letterSpacing: "-0.02em", fontWeight: "900" }],
        "body-md": ["16px", { lineHeight: "24px", fontWeight: "400" }],
        "headline-lg-mobile": ["32px", { lineHeight: "38px", fontWeight: "700" }],
        "display-xl": ["80px", { lineHeight: "80px", letterSpacing: "-0.04em", fontWeight: "900" }],
      },
    },
  },
};